### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by fredj** [Geoportail-Luxembourg/LuxMob#7]
on `make android` is password is requested (`[input] Please enter keystore password (store:app_signing.keystore):`). it should be documented how to get this password.

**Comment by pgiraud** [comment]
You're right. So the documentation should tell to ask Jeff Konen or any other maintainer.

**Comment by fredj** [comment]
Is it possible to sign with a "dev" key; just to be able to upload the apk to a device?

**Comment by jaykayone** [comment]
afaik there is a make target for debugging

**Comment by fredj** [comment]
Thanks @jaykayone `make android-debug` build and upload the app to a connected phone.
